### ISSUE TITLE
"File is not a valid JSHint library" in latest JSHint (2.5.10)

### ISSUE THREAD

**Issue by AlexanderOMara** [eclipsesource/jshint-eclipse#102]
Attempting to use the "Provide a custom JSHint library file" preference with `jshint.js` version `2.5.10` results in the the following error in the dialog.

> File is not a valid JSHint library

If I point it at a `jshint.js` version `2.5.6` I have (not the built-in one) it works, but `2.5.10` results in this error. Note this issue may not be new in `2.5.10`, I haven't tried `2.5.7` - `2.5.9`.

**Comment by kevinprotoss** [comment]
+1

**Comment by bardware** [comment]
recent 2.8.0 doesn't work either :(

**Comment by Katharsas** [comment]
+1for  2.8.0

**Comment by pavelhoral** [comment]
Played with this a bit and it is caused by some non-working global scope detection. This can be workarounded if you replace `var window = {};` with `var window = this;` at the beginning of the JS file (tested with 2.9.0).

All in all this is JSHint vs Rhino integration issue.

**Comment by paulvi** [comment]
See https://github.com/thallgren/jshint-eclipse/tree/eclipse-mars-and-jshint-2.9.0 and #110
