### ISSUE TITLE
the URL of JSHint integration for the Eclipse IDE does not work

### ISSUE THREAD

**Issue by NorthFacing** [eclipsesource/jshint-eclipse#108]
When i try to add JSHint plugin to the Ecllpse IDE, I just got the wrong msg like below :

![image](https://cloud.githubusercontent.com/assets/5105535/8430902/b049735c-1f67-11e5-8811-6c0c551f61e2.png)

So, how could I fix it ?

**Comment by paulvi** [comment]
Wrong `.` in the end?

**Comment by NorthFacing** [comment]
@paulvi It seems not because of that. But the same URL is work today.Just don't know why....
