### ISSUE TITLE
JSHint not working in Eclipse Mars

### ISSUE THREAD

**Issue by micronaut** [eclipsesource/jshint-eclipse#116]
We installed the plugin in Eclipse Luna and Mars, and have configured it to look at a single JS file to see if we can get it to work.  We have enabled JSHint violations and added several types of violations, but no warnings/errors appear in the JavaScript editor.  
Is there some way we can tell if the plugin is not running for some reason?  We looked at the Eclipse .log file, but nothing appears related to plugin failure.  Is there a way to trigger the validation of the JS file manually, or is it supposed to be live as you edit?

Thanks!

**Comment by paulvi** [comment]
Please ask on stackoverflow.com and add link here

**Comment by ralfstx** [comment]
It's working for me with Mars. Note that you have to enable jshint per project, in the project properties.

**Comment by micronaut** [comment]
We have enabled it for the project, and are trying to lint a single file.  Is this supposed to be triggered as we save the files, or do we have to trigger the lint somehow?  Is there any type of logging we can look at for the plugin?

**Comment by ralfstx** [comment]
Yes, files are linted on save. There's no debug logging but in case of problems you should find something in the error log (Open Problems View).

**Comment by micronaut** [comment]
I created a separate small project and the plugin works fine.  We have several hundred JS files in our project, so maybe it is the size of the project.
Thanks for your help.

**Comment by micronaut** [comment]
It turns out that it was a bug with Eclipse that was causing the build process to go into an infinite loop before it could execute the JSHint.
[Bug report](https://bugs.eclipse.org/bugs/show_bug.cgi?id=471904)
Thanks again for your help.
Eric
